{{- if .Values.urlService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-service-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    {{- if .Values.urlService.ingress.host }}
    - host: {{ .Values.urlService.ingress.host | quote }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: url-service
                port:
                  number: {{ .Values.urlService.service.port }}
          - path: /api/v1/urls
            pathType: Prefix
            backend:
              service:
                name: url-service
                port:
                  number: {{ .Values.urlService.service.port }}
          - path: /documentation
            pathType: Prefix
            backend:
              service:
                name: url-service
                port:
                  number: {{ .Values.urlService.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redirect-service
                port:
                  number: {{ .Values.redirectService.service.port }}
{{- end }}
