apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lynk-url-shortener
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ngqkhai/lynk-url-shortener.git'
    targetRevision: HEAD
    path: infra/k8s/helm/lynk-services
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lynk-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
